// <auto-generated />
namespace ElectronicStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.4.0")]
    public sealed partial class elect9 : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(elect9));
        
        string IMigrationMetadata.Id
        {
            get { return "202002201206443_elect9"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
